/*DATA*/
export const skills = [
    { cat: "Frontend", items: ["React.js", "Next.js", "TypeScript", "Tailwind CSS", "HTML & CSS", "Framer Motion"] },
    { cat: "Backend & DB", items: ["Node.js", "Express.js", "Python", "Django", "PostgreSQL", "MongoDB"] },
    { cat: "Tools & Cloud", items: ["Git & GitHub", "Docker", "Linux", "Postman", "Vercel"] },
];

export const projects = [
    {
        id: "01",
        slug: "colossus",
        emoji: "🔗",
        bg: "#0e1520",
        image: "/images/Colossus.png",
        title: "Colossus",
        tag: "Full Stack · Featured",
        desc: "Many drives. One titan. Merge multiple Google Drive accounts into a single unified storage pool with automatic file chunking.",
        longDesc: "Colossus is a full-stack web application that solves a universal problem — running out of Google Drive storage. Instead of paying for more space, Colossus lets you link multiple Google accounts and treats all their combined free storage as a single, seamless drive. Files are automatically chunked and distributed across accounts, then reassembled transparently on download.",
        github: "https://github.com/RihalMahmood/Colossus",
        features: [
            "Link unlimited Google accounts via OAuth 2.0 and pool their storage",
            "Automatic file chunking — files split and distributed across accounts intelligently",
            "Transparent reassembly on download — no manual steps required",
            "Session-based authentication with JWT for secure multi-account management",
            "Real-time storage usage dashboard showing per-account and aggregate stats",
            "Upload progress tracking with chunked upload feedback",
        ],
        challenges: "The trickiest part was implementing reliable file chunking and reassembly across different Google Drive accounts without data loss or ordering errors. Handling OAuth token refresh for multiple accounts simultaneously, and designing the chunk-mapping metadata schema in MongoDB to be both space-efficient and query-friendly required multiple iterations.",
        techs: ["React", "Vite", "Tailwind CSS", "DaisyUI", "Node.js", "Express", "MongoDB + Mongoose", "JWT", "Google OAuth 2.0", "Google Drive API v3"],
        year: "2024",
        type: "Full Stack Web App",
    },
    {
        id: "02",
        slug: "draftsense",
        emoji: "🧠",
        bg: "#0e1a12",
        image: "/images/DraftSense.png",
        title: "DraftSense",
        tag: "AI · Full Stack",
        desc: "An AI-powered Live League of Legends champion draft advisor.",
        longDesc: "DraftSense is a real-time AI draft advisor for League of Legends. During champion select, players can enter the current draft state and receive AI-powered champion recommendations, counter-pick suggestions, and team composition analysis. It pulls live champion data from Riot's Data Dragon API and feeds it into a local LLM for fast, context-aware advice.",
        github: "https://github.com/RihalMahmood/DraftSense",
        features: [
            "Real-time draft input with live champion search and filtering by role",
            "AI-generated counter-pick recommendations powered by a local LLM",
            "Team composition strength analysis (engage, poke, split-push, etc.)",
            "Full champion database synced from Riot Data Dragon API",
            "Role-specific pick suggestions with win-rate context",
            "Secure API with Helmet, rate limiting, and Zod input validation",
        ],
        challenges: "Integrating a local LLM with acceptable response times for a real-time use case was the core challenge. The draft state had to be serialized into a compact, context-rich prompt so the model could reason about 150+ champions without token overflow. Managing async data fetching for both the Riot API and the AI service with TanStack Query required careful cache invalidation design.",
        techs: ["React", "TypeScript", "Zustand", "Tailwind CSS", "Framer Motion", "TanStack Query", "Node.js + Express", "MongoDB + Mongoose", "Riot Data Dragon API", "Zod", "Helmet + Rate Limiter"],
        year: "2024",
        type: "AI-Powered Web App",
    },
    {
        id: "03",
        slug: "gazi-fan",
        emoji: "🛒",
        bg: "#1a0e14",
        image: "/images/Gazi_Fan.png",
        title: "Gazi Fan Commercial Website",
        tag: "E-Commerce · MERN",
        desc: "A commercial-grade MERN stack e-commerce platform for Gazi Fan, featuring product filtering, session-based shopping carts, and secure JWT authentication.",
        longDesc: "A full production e-commerce platform built for Gazi Fan, a Bangladeshi consumer electronics brand. The site supports the complete shopping lifecycle — product browsing, category filtering, cart management, and user authentication. Designed to be maintainable and scalable by a non-technical business owner, with a clean admin interface for product management.",
        github: "https://github.com/RihalMahmood/Gazi-Fan-Website",
        features: [
            "Product catalogue with category filtering and search",
            "Session-based shopping cart that persists across page refreshes",
            "Secure user authentication with JWT and bcryptjs password hashing",
            "Admin panel for adding, editing, and removing products",
            "Responsive design optimised for mobile shoppers",
            "MongoDB Atlas cloud database for zero-maintenance hosting",
        ],
        challenges: "Balancing a clean customer-facing UI with a functional admin experience in a single codebase required thoughtful route protection and role-based rendering. Integrating DaisyUI on top of Tailwind while keeping the brand identity consistent — avoiding the generic DaisyUI look — took significant customization effort.",
        techs: ["React", "React Router DOM v6", "Tailwind CSS", "DaisyUI", "Node.js + Express", "MongoDB Atlas", "bcryptjs"],
        year: "2024",
        type: "E-Commerce Platform",
    },
    {
        id: "04",
        slug: "chess-game",
        emoji: "♟",
        bg: "#12100e",
        image: "/images/Chess.png",
        title: "Chess Game",
        tag: "Desktop · Java",
        desc: "A complete two-player chess game with a JavaFX GUI, full rule enforcement, and game management features.",
        longDesc: "A fully featured desktop chess application built in Java with a JavaFX graphical interface. The game implements the complete FIDE chess ruleset including special moves, check/checkmate/stalemate detection, and move validation. Originally built as a university course project for Programming Language-II, it grew into a polished desktop app with multiple game management features.",
        github: "https://github.com/RihalMahmood/Chess-game-using-Java",
        features: [
            "Full FIDE rule enforcement: castling, en passant, pawn promotion",
            "Real-time check, checkmate, and stalemate detection",
            "Legal move highlighting — click a piece to see all valid squares",
            "Move history panel with algebraic chess notation",
            "New game, undo last move, and resign controls",
            "Clean JavaFX UI with smooth piece drag-and-drop",
        ],
        challenges: "Implementing the complete chess ruleset without a library was the primary challenge — especially edge cases like pin detection (a piece can't move if doing so exposes the king to check), and recursive checkmate detection that must simulate future board states. Designing the board model so that both the UI and the game logic could read it efficiently without tight coupling required a clean MVC separation.",
        techs: ["Java", "JavaFX", "Maven", "JUnit"],
        year: "2023",
        type: "Desktop Application",
    },
];

export const contacts = [
    { icon: "E", label: "Email", val: "rihalmahmood@gmail.com", href: "mailto:rihalmahmood@gmail.com" },
    { icon: "GH", label: "GitHub", val: "github.com/RihalMahmood", href: "https://github.com/RihalMahmood" },
    { icon: "LI", label: "LinkedIn", val: "linkedin.com/in/rihalmahmood", href: "https://www.linkedin.com/in/quazi-rihal-mahmood-05a59b362/" },
];

export const socials = [
    { name: "GitHub", url: "https://github.com/RihalMahmood" },
    { name: "LinkedIn", url: "https://www.linkedin.com/in/quazi-rihal-mahmood-05a59b362/" },
    { name: "Instagram", url: "https://www.instagram.com/quazi_rihal/" },
];
